apiVersion: 1
datasources:
  - name: NetProspect-Prometheus
    type: prometheus
    uid: netprospect-fleet
    access: proxy
    url: http://hel1-prometheus:9090
    isDefault: true
    editable: true
  - name: Loki
    type: loki
    uid: netprospect-loki
    access: proxy
    url: http://100.95.20.65:3100
    isDefault: false
    editable: true
  - name: Jaeger
    type: jaeger
    uid: netprospect-jaeger
    access: proxy
    url: http://100.114.17.74:16686
    isDefault: false
    editable: true
